import type { Metadata } from "next";
import "@/styles/globals.css";
import { Header } from "@/components/header";
import { notoSansKR } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${notoSansKR.className} antialiased w-full overflow-x-hidden bg-bg-default`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
