import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Header } from "@/components/header";
import { DarkTheme } from "@/components/dark-theme";
import { notoSansKR } from "@/components/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.className} antialiased`}>
        <DarkTheme />
        <div className="wrapper overflow-hidden main">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
